version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tracery
    binary: tracery
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - id: tracery
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - src: examples/*.yaml
        dst: examples

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: riyacore404
    name: tracery
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"